/*
 * embedded_assets.c — Generated file mapping URL paths to embedded bytes.
 * DO NOT EDIT — regenerated by scripts/embed-frontend.sh
 */
#include "ui/embedded_assets.h"
#include <string.h>

extern const unsigned char _binary_assets_index_BBe1IJI4_css_data[];
extern const unsigned int _binary_assets_index_BBe1IJI4_css_size;
extern const unsigned char _binary_assets_index_DdnuZL9e_js_data[];
extern const unsigned int _binary_assets_index_DdnuZL9e_js_size;
extern const unsigned char _binary_index_html_data[];
extern const unsigned int _binary_index_html_size;

cbm_embedded_file_t CBM_EMBEDDED_FILES[] = {
    {"/assets/index-BBe1IJI4.css", _binary_assets_index_BBe1IJI4_css_data, 0, "text/css"},
    {"/assets/index-DdnuZL9e.js", _binary_assets_index_DdnuZL9e_js_data, 0, "application/javascript"},
    {"/index.html", _binary_index_html_data, 0, "text/html"},
};
const int CBM_EMBEDDED_FILE_COUNT = 3;

static void __attribute__((constructor)) init_embedded_sizes(void) {
    cbm_embedded_file_t *files = CBM_EMBEDDED_FILES;
    files[0].size = _binary_assets_index_BBe1IJI4_css_size;
    files[1].size = _binary_assets_index_DdnuZL9e_js_size;
    files[2].size = _binary_index_html_size;
}

const cbm_embedded_file_t *cbm_embedded_lookup(const char *path) {
    for (int i = 0; i < CBM_EMBEDDED_FILE_COUNT; i++) {
        if (strcmp(CBM_EMBEDDED_FILES[i].path, path) == 0) {
            return &CBM_EMBEDDED_FILES[i];
        }
    }
    return NULL;
}
