const NODE_LABELS_ZH: Record<string, string> = {
  File: "文件",
  Folder: "目录",
  Module: "模块",
  Package: "包",
  Namespace: "命名空间",
  Project: "项目",
  Branch: "分支",
  Section: "区段",
  Type: "类型",
  Class: "类",
  Struct: "结构体",
  Interface: "接口",
  Trait: "特征",
  Enum: "枚举",
  Union: "联合类型",
  TypeAlias: "类型别名",
  Function: "函数",
  Method: "方法",
  ExternalType: "外部类型",
  ExternalMethod: "外部方法",
  ExternalPackage: "外部包",
  Constructor: "构造函数",
  Variable: "变量",
  Constant: "常量",
  Property: "属性",
  Field: "字段",
  Parameter: "参数",
  Decorator: "装饰器",
  Annotation: "注解",
  Macro: "宏",
  Component: "组件",
  Hook: "钩子",
  Route: "路由",
  Endpoint: "端点",
  Query: "查询",
  Mutation: "变更",
  Subscription: "订阅",
  Table: "数据表",
  Column: "列",
  Index: "索引",
  Model: "模型",
  Service: "服务",
  Controller: "控制器",
  Repository: "仓库",
  Event: "事件",
  Channel: "通道",
  Command: "命令",
  Handler: "处理器",
  Test: "测试",
};

const RELATIONSHIP_LABELS_ZH: Record<string, string> = {
  DEFINES: "定义",
  DECLARES: "声明",
  CONTAINS: "包含",
  CALLS: "调用",
  IMPORTS: "导入",
  IMPORTS_FROM: "从中导入",
  EXPORTS: "导出",
  INHERITS: "继承",
  EXTENDS: "扩展",
  IMPLEMENTS: "实现",
  USES: "使用",
  REFERENCES: "引用",
  READS: "读取",
  WRITES: "写入",
  OVERRIDES: "重写",
  RETURNS: "返回",
  PARAMETER_OF: "作为参数",
  TYPE_OF: "类型为",
  DEPENDS_ON: "依赖",
  ROUTES_TO: "路由到",
  HANDLES: "处理",
  TRIGGERS: "触发",
  PUBLISHES: "发布",
  SUBSCRIBES: "订阅",
  RELATED_TO: "关联",
  HAS_METHOD: "拥有方法",
  INSTANTIATES: "实例化",
  SIMILAR_TO: "相似",
  USAGE: "使用",
  SEMANTICALLY_RELATED: "语义相关",
  HTTP_CALLS: "HTTP 调用",
  CONTAINS_FILE: "包含文件",
  CONTAINS_FOLDER: "包含目录",
  CONFIGURES: "配置",
  DEFINES_METHOD: "定义方法",
  RAISES: "抛出异常",
  TYPE_REFERENCE: "类型引用",
  TYPE_ASSIGNMENT: "类型赋值",
  READS_ENV: "读取环境变量",
  WRITES_ENV: "写入环境变量",
  SENDS: "发送",
  RECEIVES: "接收",
  TESTS: "测试",
  IMPLEMENTED_BY: "由其实现",
  INHERITED_BY: "由其继承",
  CROSS_REPO_CALLS: "跨仓库调用",
  CROSS_REPO_IMPORTS: "跨仓库导入",
  CROSS_PACKAGE_IMPORTS: "跨项目包导入",
  CROSS_PROJECT_DEPENDS: "跨项目依赖",
};

const STATUS_LABELS_ZH: Record<string, string> = {
  live: "活跃",
  dead: "死代码",
  entry: "入口",
  test: "测试",
  unknown: "未知",
};

export function graphNodeLabel(label: string): string {
  return NODE_LABELS_ZH[label] ?? label;
}

export function graphRelationshipLabel(type: string): string {
  return RELATIONSHIP_LABELS_ZH[type] ?? type.replace(/_/g, " ").toLowerCase();
}

export function graphStatusLabel(status: string): string {
  return STATUS_LABELS_ZH[status] ?? status;
}
